### ISSUE TITLE
最新版的好像ehole功能无法使用

### ISSUE THREAD

**Issue by ggforlove** [lemonlove7/dirsearch_bypass403#10]
Task Completed
Traceback (most recent call last):
  File ".\dirsearch.py", line 205, in <module>
    main()
  File ".\dirsearch.py", line 199, in main
    ehole()
  File ".\dirsearch.py", line 165, in ehole
    import ehole.ehole
ModuleNotFoundError: No module named 'ehole.ehole'; 'ehole' is not a package

**Comment by lemonlove7** [comment]
已修复

<img width="1414" height="522" alt="Image" src="https://github.com/user-attachments/assets/039e281b-8605-4087-b677-5825f84cff7c" />
