### ISSUE TITLE
逻辑问题

### ISSUE THREAD

**Issue by cqrlhz** [lemonlove7/dirsearch_bypass403#4]
[02:17:44] Starting:

Task Completed
Start JsFind!
Find 0 URL:
Start testing for survival!

Find 0 Subdomain:
No 403 status code present!
fingerprint identification!
Traceback (most recent call last):
  File "/root/dirsearch_bypass403/dirsearch.py", line 205, in <module>
    main()
  File "/root/dirsearch_bypass403/dirsearch.py", line 199, in main
    ehole()
  File "/root/dirsearch_bypass403/dirsearch.py", line 173, in ehole
    ehole.ehole.start_ehole()
  File "/root/dirsearch_bypass403/ehole/ehole.py", line 10, in start_ehole
    with open(f1) as d:
         ^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/dirsearch_bypass403/reports/https_api.0yeex2e.com/_23-09-07_02-17-44.txt'

**Comment by chenroot1** [comment]
解决了吗？

**Comment by lemonlove7** [comment]
<img width="895" height="325" alt="Image" src="https://github.com/user-attachments/assets/07abac1d-e7a2-4ef6-878c-136fcc91ec2e" />
